### PR TITLE
To get zip code back by modifying database id value in netacuity

### PR DESCRIPTION
**Pull request by krishnaramya**
This change is for returning zip code back. So updated database id as '4'.
Please peer review @chrisryan

### CODE REVIEW

**Comment by chrisryan** [comment]
:+1: I don't see any problems with the changes.
@chadicus @raybot can we discuss getting this merged/tagged so we can use in the api? Do we need to tag 2.0, since it changes the return values?

**Comment by chadicus** [comment]
@chrisryan I don't think we'll need to go to v2 if you append the return values to the end of the array instead of in the middle.

**Comment by chrisryan** [comment]
some values were also removed because the request that has the extra data we needed did not include it all.

**Comment by chadicus** [comment]
yeah, I saw that, so we will have to go to version 2

**Comment by krishnaramya** [comment]
Currently I have placed "placeholders" and going to replace all those placeholders. Please don't merge this one.

**Comment by chrisryan** [comment]
:+1: @chadicus this is ready now with the correct names for all fields.

**Pull request merged**
